language: r
sudo: required
cache: packages
warnings_are_errors: false
apt_packages:
  - libudunits2-dev
r_packages:
  - covr
matrix:
  include:
  - r: devel
  - r: release
    after_success:
    - Rscript -e 'covr::codecov()'
  - r: oldrel
